net-radio-db-storage:
  image: busybox:latest
  volumes:
    - /var/lib/mysql

net-radio-db:
  image: mysql:5
  volumes:
    - /etc/localtime:/etc/localtime:ro
  volumes_from:
    - net-radio-db-storage
  environment:
    - MYSQL_ROOT_PASSWORD=password
    - MYSQL_DATABASE=net-radio

net-radio-archive:
  build: net-radio-archive
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /net-radio:/net-radio:rw
  links:
    - net-radio-db:net-radio.db
  environment:
    - NRA_DB_HOST=net-radio.db
    - NRA_DB_USER=root
    - NRA_DB_PASSWORD=password
    - NRA_DB_NAME=net-radio
    - NRA_WORKING_FILES_RETENTION_PERIOD_DAYS=7
    - NRA_FORCE_MP4=true
    - NRA_ARCHIVE_FILES_RETENTION_PERIOD_DAYS=60
