# cronからは常にproduction環境で起動します
# 基本的にはこちらのみ設定してください
production:

    # ファイルを保存(archive)するディレクトリを設定してください（フルパス）
    # このディレクトリ以下にサブディレクトリやファイルが作成されます
    # cronが実行されるユーザーにrwxのpermissionが与えられるようにしてください
    archive_dir: /net-radio/archive

    # ダウンロード中などにファイルを一時的に置いておくディレクトリを設定してください（フルパス）
    # 一時的とはいえ、デフォルトで事故防止のためこのディレクトリのデータは30日ほど削除されません (lib/main/workaround.rbのrm_working_filesを参照)
    # そのためそれなりにおおきな容量となります
    # cronが実行されるユーザーにrwxのpermissionが与えられるようにしてください
    working_dir: /net-radio/working

    # 作業時に残ったファイル(mp4に変換前のflv dumpなど)を残しておく日数です
    # 何か事故が起きた時に使えるかもしれない
    working_files_retention_period_days: <%= ENV['NRA_WorkingFilesRetentionPeriodDays'] %>

    # radikoで録音するチャンネルを設定してください
    # channel code (QRRなど) についてはREADME.mdのFAQを参照してください
    radiko_channels:
      <% ENV['NRA_RADIKO_CHANNELS'].split(',').each do |c| %>
        - <%= c %>
      <% end if ENV['NRA_RADIKO_CHANNELS'] %>

    # らじるらじるで録音するチャンネルを設定してください
    radiru_channels:
      <% ENV['NRA_RADIRU_CHANNELS'].split(',').each do |c| %>
        - <%= c %>
      <% end if ENV['NRA_RADIRU_CHANNELS'] %>

    # ファイル名に含まれる単語からシムリンクを作成
    # archive_dirで設定したディレクトリ配下に 0_selections ディレクトリの作成、配下にシムリンク
    # 定期的に聴きたいラジオをより分けるのに便利です
    #selections:
    #    - 花澤香菜
    #    - 佐倉綾音
    #    - モモノキ

    # trueの場合、音声のみのコンテンツ(音泉、アニたま、Radiko、らじるらじる)を保存時に強制的にmp4へ変換します(再エンコードはかけないので音声は劣化しません)
    # Googleフォトなどにバックアップする際に便利です
    force_mp4: <%= ENV['NRA_FORCE_MP4'] %>

    # AG-ON (導入難易度高め。詳しくはREADME参照)
    # 録画しない場合はこの項目ごと消すと何もしません
    # これのみSelenium WebDriverを使っていたり、ffmpegでHLSを処理していたりと特殊なので
    # その辺が原因で動かない可能性もあります。エラーがでたらとりあえず項目消してみてください
    <% if ENV['NRA_AGON_MAIL'] != "" && ENV['NRA_AGON_PASSWORD'] != "" %>
    agon:
         mail: <%= ENV['NRA_AGON_MAIL'] %>
         password: <%= ENV['NRA_AGON_PASSWORD'] %>
         headless: true
    <% end %>

    #    # Seleniumの実行にheadless gemとxvfbを使用するか
    #    # falseの場合はSeleniumでfirefoxが普通に起動するようにしておいてください
    #    #   (LinuxであればDISPLAY環境変数がセットされているように)
    #    #   Mac OS Xの場合は基本的にfalseにしてください
    #    # trueの場合はxvfbをインストールしておいてください (Ubuntu/Debianであれば `apt-get install xvfb`)
    #    headless: false
    # ニコニコ(開発中。恐ろしく不安定) おそらくプレミアム会員必須
    # 録画しない場合はこの項目ごと消すと何もしません
    #niconico:
    #    username: 'USERNAME'
    #    password: 'PASSWORD'
    #    live:
    #        # 録画(タイムシフトの取得)をしたい生放送をキーワードで指定
    #        keywords:
    #            - '村川梨衣'
    #            - '麻倉もも'
    #        # wikipediaのカテゴリで検索キーワードを一括指定できます
    #        keyword_wikipedia_categories:
    #            - '声優ユニット'
    #            - '日本の女性声優'

development:
    radiko_channels:
        - QRR # bunka housou
        - LFR # nippon housou
    archive_dir: /tmp/net-radio-archive
    working_dir: /tmp/net-radio-working
